import "@bitnation-dev/management/dist/common"

declare global {
    export type Unit = {
            projectId: string
            slug: string
            totalAmount: number,
            percentToSetAside: number
            percentToSettle: number
            percentOnDelivery: number
            preSellStartDate: number
            preSellEndDate: number
            constructionStartDate: number
            constructionEndDate: number
        }

    export type WooCommerceWebhook = 'order.created' | 'order.updated' | 'order.deleted' | 'product.updated'

    export type WooCommerceStore = {
        id: number
        data: {
            storeUrl: string
            divisionId: number
            webhooks: WooCommerceWebhook[]
            webhookSecret?: string  // Generated by backend, used to verify webhook signatures
            accounts?: {
                DOP?: number
                USD?: number
                EUR?: number
            }
        }
    }
}

export {}